import {
    BellIcon,
    Briefcase,
    ContactIcon,
    Crown,
    FileText,
    FormInput,
    GalleryThumbnails,
    Layers,
    LayoutDashboard,
    Package,
    Settings2,
    ShieldUserIcon,
    User,
    Users,
    Users2,
    Image,
    Plus,
    Bell
  } from "lucide-react";
  
  export const data = {
    user: {
      name: "admin",
      email: "admin@admin.com",
      avatar: "/user.jpg",
    },
    teams: [
      {
        name: "Sewzee",
        logo: Crown,
        plan: "Super Admin",
      },
      {
        name: "Sewzee",
        logo: ShieldUserIcon,
        plan: "Admin",
      },
    ],
    navMain: [
      {
        title: "Dashboard",
        url: "/dashboard",
        icon: LayoutDashboard,
        isActive: true,
        items: [],
        roles: ["super_admin", "admin"],
      },
      {
        title: "Users",
        url: "/dashboard/users",
        icon: Users,
        isActive: true,
        items: [],
        roles: ["admin"],
      },
      {
        title: "Category",
        url: "/dashboard/category",
        icon: Users2,
        isActive: true,
        items: [],
        roles: ["admin"],
      },{
        title: "Sub Category",
        url: "/dashboard/sub_category",
        icon: Users2,
        isActive: true,
        items: [],
        roles: ["admin"],
      },{
        title: "Brand",
        url: "/dashboard/brand",
        icon: Users2,
        isActive: true,
        items: [],
        roles: ["admin"],
      },{
        title: "Breed",
        url: "/dashboard/breed",
        icon: Users2,
        isActive: true,
        items: [],
        roles: ["admin"],
      },
      {
        title: "Collection",
        url: "/dashboard/collection",
        icon: Users2,
        isActive: true,
        items: [],
        roles: ["admin"],
      },
      {
        title: "All Products",
        url: "/dashboard/product",
        icon: Package,
        isActive: true,
        items: [],
        roles: ["admin"],
      }
    ],
    // projects: [
    //   {
    //     title: "Users",
    //     url: "/dashboard/users",
    //     icon: User,
    //     isActive: true,
    //     items: [],
    //     roles: ["super_admin"],
    //   },
    //   {
    //     title: "Configuration",
    //     name: "Configuration",
    //     url: "/dashboard/configuration",
    //     icon: FormInput,
    //     items: [
    //       {
    //         title: "Home",
    //         url: "/dashboard/configuration/home",
    //       },
    //       {
    //         title: "Service",
    //         url: "/dashboard/configuration/service",
    //       },
    //       {
    //         title: "Header & Footer",
    //         url: "/dashboard/configuration/header",
    //       },
    //       {
    //         title: "Internal Pages",
    //         url: "/dashboard/configuration/internal",
    //       },
    //     ],
    //     roles: ["super_admin"],
    //   },
    //   {
    //     title: "Blogs",
    //     name: "Blogs",
    //     url: "/dashboard/blogs",
    //     icon: FileText,
    //     roles: ["super_admin"],
    //   },
    //   {
    //     title: "Contact us form",
    //     name: "Contact us form",
    //     url: "/dashboard/contact-us",
    //     icon: ContactIcon,
    //     roles: ["super_admin", "admin"],
    //   },
    // ],
    // extra: [
    //   {
    //     title: "Forms",
    //     name: "Forms",
    //     url: "/forms",
    //     icon: FormInput,
    //     roles: ["super_admin", "admin"],
    //   },
    // ],
    more: [
      {
        title: "Add Thumbnail",
        name: "Add Thumbnail",
        url: "/dashboard/add_thumbnail",
        icon: GalleryThumbnails,
        roles: ["admin"],
      },
      {
        title: "Ad Banner",
        name: "Ad Banner",
        url: "/dashboard/ad_banner",
        icon: Image,
        roles: ["admin"],
      },
      {
        title: "Header & Footer",
        name: "Header & Footer",
        url: "/dashboard/header-footer",
        icon: LayoutDashboard,
        roles: ["admin"],
      },
      {
        title: "Sliders",
        name: "Sliders",
        url: "/dashboard/sliders",
        icon: Image,
        roles: ["admin"],
      },
      {
        title: "Add Category",
        name: "Add Category",
        url: "/dashboard/add_category",
        icon: Plus,
        roles: ["admin"],
      }, 
      {
        title: "Notification",
        name: "Notification",
        url: "/dashboard/send_notification",
        icon: Bell,
        roles: ["admin"],
      },
    ],
  };
  