import {
    BellIcon,
    Briefcase,
    ContactIcon,
    Crown,
    FileText,
    FormInput,
    GalleryThumbnails,
    Layers,
    LayoutDashboard,
    Package,
    Settings2,
    ShieldUserIcon,
    User,
    Users,
    Users2,
    Image,
    Gift,
    BadgeCent,
    PackageOpen,
    Cat,
    Images,
    Tag,
    ListTree,
    PawPrint,
    Sparkle,
    BadgeCheck,
    PackagePlus,
    Receipt,
    Activity
  } from "lucide-react";
  
  export const data = {
    user: {
      name: "admin",
      email: "admin@admin.com",
      avatar: "/user.jpg",
    },
    teams: [
      {
        name: "Sewzee",
        logo: Crown,
        plan: "Super Admin",
      },
      {
        name: "Sewzee",
        logo: ShieldUserIcon,
        plan: "Admin",
      },
    ],
    navMain: [
      {
        title: "Dashboard",
        url: "/dashboard",
        icon: Activity,
        isActive: true,
        items: [],
        roles: ["super_admin", "admin"],
      },
      {
        title: "Users",
        url: "/dashboard/users",
        icon: Users,
        isActive: true,
        items: [],
        roles: ["admin"],
      },
      {
        title: "Category",
        url: "/dashboard/category",
        icon: Tag,
        isActive: true,
        items: [],
        roles: ["admin"],
      },{
        title: "Sub Category",
        url: "/dashboard/sub_category",
        icon: ListTree,
        isActive: true,
        items: [],
        roles: ["admin"],
      },{
        title: "Brand",
        url: "/dashboard/brand",
        icon: BadgeCheck,
        isActive: true,
        items: [],
        roles: ["admin"],
      },{
        title: "Breed",
        url: "/dashboard/breed",
        icon: PawPrint,
        isActive: true,
        items: [],
        roles: ["admin"],
      },
      {
        title: "Collection",
        url: "/dashboard/collection",
        icon: PackagePlus,
        isActive: true,
        items: [],
        roles: ["admin"],
      },
      {
        title: "All Products",
        url: "/dashboard/product",
        icon: Package,
        isActive: true,
        items: [],
        roles: ["admin"],
      },
      {
        title: "Orders",
        url: "/dashboard/orders",
        icon: Receipt,
        isActive: true,
        items: [],
        roles: ["admin"],
      },
    ],
    // projects: [
    //   {
    //     title: "Users",
    //     url: "/dashboard/users",
    //     icon: User,
    //     isActive: true,
    //     items: [],
    //     roles: ["super_admin"],
    //   },
    //   {
    //     title: "Configuration",
    //     name: "Configuration",
    //     url: "/dashboard/configuration",
    //     icon: FormInput,
    //     items: [
    //       {
    //         title: "Home",
    //         url: "/dashboard/configuration/home",
    //       },
    //       {
    //         title: "Service",
    //         url: "/dashboard/configuration/service",
    //       },
    //       {
    //         title: "Header & Footer",
    //         url: "/dashboard/configuration/header",
    //       },
    //       {
    //         title: "Internal Pages",
    //         url: "/dashboard/configuration/internal",
    //       },
    //     ],
    //     roles: ["super_admin"],
    //   },
    //   {
    //     title: "Blogs",
    //     name: "Blogs",
    //     url: "/dashboard/blogs",
    //     icon: FileText,
    //     roles: ["super_admin"],
    //   },
    //   {
    //     title: "Contact us form",
    //     name: "Contact us form",
    //     url: "/dashboard/contact-us",
    //     icon: ContactIcon,
    //     roles: ["super_admin", "admin"],
    //   },
    // ],
    // extra: [
    //   {
    //     title: "Forms",
    //     name: "Forms",
    //     url: "/forms",
    //     icon: FormInput,
    //     roles: ["super_admin", "admin"],
    //   },
    // ],
    more: [
      {
        title: "Add Banner",
        name: "Add Banner",
        url: "/dashboard/banners",
        icon: GalleryThumbnails,
        roles: ["admin"],
      },
      {
        title: "Ad Banner",
        name: "Ad Banner",
        url: "/dashboard/ad_banner",
        icon: Image,
        roles: ["admin"],
      },
      {
        title: "Header & Footer",
        name: "Header & Footer",
        url: "/dashboard/header-footer",
        icon: LayoutDashboard,
        roles: ["admin"],
      },
      {
        title: "Sliders",
        name: "Sliders",
        url: "/dashboard/sliders",
        icon: Images,
        roles: ["admin"],
      },
      {
        title: "Cat Life Banners",
        name: "Cat Life Banners",
        url: "/dashboard/cat-life-banner",
        icon: Cat,
        roles: ["admin"],
      },
      {
        title: "Product Banner",
        name: "Product Banner",
        url: "/dashboard/product-banner",
        icon: PackageOpen,
        roles: ["admin"],
      },
      {
        title: "HSN Codes",
        name: "HSN Codes",
        url: "/dashboard/hsn_codes",
        icon: BadgeCent,
        roles: ["admin"],
      },
      {
        title: "Coupons",
        name: "Coupons",
        url: "/dashboard/coupons",
        icon: Gift,
        roles: ["admin"],
      },
      {
        title: "Blogs",
        name: "Blogs",
        url: "/dashboard/blog",
        icon: FileText,
        roles: ["admin"],
      },
    ],
  };
  